config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'rounds#index'

  # resources :games
  # resources :players
  # resources :questions
  resources :rounds do
    member do
      post :correct_answer
      post :prev_correct_answer
      post :incorrect_answer
      post :go_to_bank
      post :reset
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord; end

app/models/player.rb
class Player < ApplicationRecord; end

app/models/question.rb
class Question < ApplicationRecord; end

app/models/round.rb
class Round < ApplicationRecord; end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @game = Game.take
  end

  def new
    
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  before_action :set_round, except: %i[index]
  before_action :set_game

  def index
    @resources = Round.all
  end

  def show; end

  def correct_answer
    @round.bank += 100
    @round.save!
  end

  def prev_correct_answer
    return if @round.bank <= 0

    @round.bank -= 100
    @round.save!
  end

  def incorrect_answer
    @round.bank = 0
    @round.save!
  end

  def go_to_bank
    @game.bank += @round.bank
    @game.save!

    @round.bank = 0
    @round.save!
  end

  def reset
    @game.bank = 0
    @game.save!

    @round.bank = 0
    @round.save!
  end

  private

  def set_round
    @round = Round.find(params[:id])
  end

  def set_game
    @game = Game.take
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/index.html.slim
p Список игр

app/views/games/new.html.slim
H1 Новая игра

p здесь отобразить добавление участников
p здесь отобразить добавление вопросов

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Handsome</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/rounds/_game_bank.html.slim
.bank
  p Банк: #{game.bank}

app/views/rounds/_round_bank.html.slim
.money
  p.money__step class="#{round.bank >= 1000 ? 'passed' : ''}" 1000
  p.money__step class="#{round.bank >= 900 ? 'passed' : ''}" 900
  p.money__step class="#{round.bank >= 800 ? 'passed' : ''}" 800
  p.money__step class="#{round.bank >= 700 ? 'passed' : ''}" 700
  p.money__step class="#{round.bank >= 600 ? 'passed' : ''}" 600
  p.money__step class="#{round.bank >= 500 ? 'passed' : ''}" 500
  p.money__step class="#{round.bank >= 400 ? 'passed' : ''}" 400
  p.money__step class="#{round.bank >= 300 ? 'passed' : ''}" 300
  p.money__step class="#{round.bank >= 200 ? 'passed' : ''}" 200
  p.money__step class="#{round.bank >= 100 ? 'passed' : ''}" 100
  p.money__step class="#{round.bank >= 0 ? 'passed' : ''}" 0

app/views/rounds/_timer.html.slim
.timer data-controller="timer"
  .wrap
    svg.progress-ring viewBox="0 0 120 120"
      circle.progress-ring__circle cx="60" cy="60" r="54"

    .display
      .time
        input.digits#minutes type="text" placeholder="00" value="05" <span class="colon">:</span>
        input.digits#seconds type="text" placeholder="00"

    .buttons
      button#reset disabled=true Сброс
      button#start Старт
 

app/views/rounds/correct_answer.turbo_stream.slim
= turbo_stream.update "round_bank" do
  = render "round_bank", round: @round

app/views/rounds/go_to_bank.turbo_stream.slim
= turbo_stream.update "round_bank" do
  = render "round_bank", round: @round

= turbo_stream.update "game_bank" do
  = render "game_bank", game: @game

app/views/rounds/incorrect_answer.turbo_stream.slim
= turbo_stream.update "round_bank" do
  = render "round_bank", round: @round

app/views/rounds/index.html.slim
= render "game_bank", game: @game

- @resources.each do |round|
  p = link_to round.name, round_path(round) 

app/views/rounds/prev_correct_answer.turbo_stream.slim
= turbo_stream.update "round_bank" do
  = render "round_bank", round: @round

app/views/rounds/reset.turbo_stream.slim
= turbo_stream.update "round_bank" do
  = render "round_bank", round: @round

= turbo_stream.update "game_bank" do
  = render "game_bank", game: @game

app/views/rounds/show.html.slim
.show-round data-controller="keys_listener"
  = turbo_frame_tag "round_bank" do
    = render "round_bank", round: @round

  = turbo_frame_tag "game_bank" do
    = render "game_bank", game: @game

  .timer-container
    = render 'timer'

  .hidden-block
    = link_to "Верно", correct_answer_round_path, method: :post, "data-action"=>"keydown.up@window->keys_listener#upHandler", id: "up-link"
    = link_to "Не верно", incorrect_answer_round_path, method: :post, "data-action"=>"keydown.left@window->keys_listener#leftHandler", id: "left-link"
    = link_to "Банк", go_to_bank_round_path, method: :post, "data-action"=>"keydown.right@window->keys_listener#rightHandler", id: "right-link"
    = link_to "Предыдущий шаг", prev_correct_answer_round_path, method: :post, "data-action"=>"keydown.down@window->keys_listener#downHandler", id: "down-link"
    = link_to "Сбросить", reset_round_path, method: :post, "data-action"=>"keydown.esc@window->keys_listener#escHandler", id: "esc-link"